export const BOARD_MOVE_UPDATE = "BOARD_MOVE_UPDATE";
export const BOARD_MOVE_UNDO = "BOARD_MOVE_UNDO";
export const BOARD_FEN_UPDATE = "BOARD_FEN_UPDATE";
export const BOARD_PGN_UPDATE = "BOARD_PGN_UPDATE";
